<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="KATAKURI.local" name="testPackage.JavaObjModel1.BrokenLinks" tests="6" failures="0" timestamp="30 Jan 2019 13:06:20 GMT" time="108.049" errors="1">
  <testcase name="list1" time="108.049" classname="testPackage.JavaObjModel1.BrokenLinks">
    <error type="java.lang.ClassCastException" message="sun.net.www.protocol.mailto.MailToURLConnection cannot be cast to java.net.HttpURLConnection">
      <![CDATA[java.lang.ClassCastException: sun.net.www.protocol.mailto.MailToURLConnection cannot be cast to java.net.HttpURLConnection
at testPackage.JavaObjModel1.BrokenLinks.list1(BrokenLinks.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- list1 -->
  <testcase name="canonical_links2" classname="testPackage.JavaObjModel1.BrokenLinks">
    <skipped/>
  </testcase> <!-- canonical_links2 -->
  <testcase name="canonical_links3" classname="testPackage.JavaObjModel1.BrokenLinks">
    <skipped/>
  </testcase> <!-- canonical_links3 -->
  <testcase name="canonical_links1" classname="testPackage.JavaObjModel1.BrokenLinks">
    <skipped/>
  </testcase> <!-- canonical_links1 -->
  <testcase name="canonical_links" classname="testPackage.JavaObjModel1.BrokenLinks">
    <skipped/>
  </testcase> <!-- canonical_links -->
  <testcase name="addItems" classname="testPackage.JavaObjModel1.BrokenLinks">
    <skipped/>
  </testcase> <!-- addItems -->
</testsuite> <!-- testPackage.JavaObjModel1.BrokenLinks -->
